services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://3.144.115.3:8000
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    networks:
      - app-network

networks:
  app-network:
    external: true