services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://3.22.51.141:8000
    networks:
      - app-network

networks:
  app-network:
    external: true 